### ISSUE TITLE
Code Review Party

### ISSUE THREAD

**Issue by cmarley3-14** [sneakysnakesfrc/robot-2020#1]
Hello! I am Christopher Marley, a co-lead programmer of FRC Team 4681, Murphy's Law, and I have been assigned your repository as part of the [Chief Delphi "2020 Code Review Party"](https://www.chiefdelphi.com/t/2020-code-review-party/382427). Over the next two weeks, I will be plumbing the depths of your code and compiling everything in this one issue (so your emails aren't 'pinged' too much).
_Quick disclaimer, our team uses_ `TimedRobot`, _so forgive me if my knowledge of command based is lacking. I did do a lot of research on the features, so I should be up to speed._
If you have any questions at all, reply to this issue or directly email me at chrismarley3.14@gmail.com.
_I'm very surprised there have been no issues opened in this repo... cool!_

**Comment by cmarley3-14** [comment]
I have my notes compiled, but it is 11:30 where I live so I'll sleep and input them tomorrow. I did not forget; I procrastinated (like a good and proper teenager (and robotics student)).

**Comment by cmarley3-14** [comment]
Alright! Thank you for a legible, easy to read, well documented, robot program. Just for reference,
>**Features:** New command-based style Shooter flywheel motion   profile Drivetrain motion profile and trajectory following for autos (we got   6 ball and 5 ball autos working stable in the event) Vision target aligning   using chameleon vision( we used raspberry pi as a server so we had 2 servers   running, RoboRIO and raspberry pi) Also we have a shuffleboard UI which our   code runs synchronized with.   https://github.com/sneakysnakesfrc/sneaky-shuffleboard-2020

> **Areas to Examine:** Coding convention and style, Any possible improvements in our control loops (Feedback and feedforward) and our project structure

I feel like control loops are an experimental tuning process. I don't know how y'all would like me to examine those. If you still want that, email me at chrismarley3.14@gmail.com or reply to the issue and I'll try to respond in three days. All in all, the code is pretty good. Coming from a `TimedRobot` background that doesn't use anything fancy in terms of encoders (though, we successfully started using a Talon connected to a gearbox encoder), your drivetrain and trajectory features were rather lost to me, but no doubt they are cool and serve you well. Okay, let's get to the meat.

* [`Constants.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/Constants.java) - I like how you used nested classes to specify constants for different subsystems, and then only need to import them for each subsystem. It's very compact.
* [`Robot.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/Robot.java) - When a project shell is created, WPILib encourages Strings as an auto selector. I'm looking here and thinking, "man, ints really are better for space and time." But then, why not use bytes? 😁 Our team had various Lamborghinis as auto Strings.
* [`RobotContainer.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/RobotContainer.java) - That's a lot of code commented out. Otherwise, nothing alarming here.
* [`SneakyTrajectory.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/trajectories/SneakyTrajectory.java) - Thank goodness for declaring multiple Trajectories in one line!
* [`subsystems/ShooterSubsystem.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/subsystems/ShooterSubsystem.java) - The function at L45 could be a constant, but GitHub says the function isn't used either. 😕 
* [`subsystems/StatusLED.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/subsystems/StatusLED.java) - The [default](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/subsystems/StatusLED.java#L42) case in the switch statement is missing a break statement. `m_statusLED.setData(m_ledBuffer);` is called repeatedly. You can pull it out of the switch cases because it's already called in `setLEDColorValue()`, or if I'm reading incorrectly, you can pull it under the switch statement.
* [`commands/RunHopper.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/RunHopper.java) - I believe you are re-initializing variables every execution, and then you have a [value used without a variable attached unlike the others](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/RunHopper.java#L48).
* [`commands/ToggleClimb.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/ToggleClimb.java) - Why does this exist alongside the two other commands for [close](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/CloseClimb.java) and [open](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/OpenClimb.java)? I'd prefer two buttons for close and open rather than a button that toggles between them.
* [`commands/ToggleCompressor.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/ToggleCompressor.java) - Similar here. My question is why one would toggle the compressor manually, or not leave it to automation, or... I don't quite understand the purpose, I guess.
* [`commands/ToggleLED.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/ToggleLED.java) - Unlike the Climber, LEDs are an easy visual state so I understand a toggle here. The question then becomes why are there [CloseLED](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/CloseLED.java) and [OpenLED](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/OpenLED.java) commands?

Other things that aren't issues but I found interesting:
* [`subsystems/HopperSubsystem.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/subsystems/HopperSubsystem.java) - I learned a new naming convention: prior underscore!
* [`commands/VisionTurnCG.java L25`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/VisionTurnCG.java#L25) - This is the funniest things I've read because it's exactly like a sentence. You can read it left to right and it makes sense (applying Command Based vocab here and there and etc.).
* [`commands/VisionTurnPF.java L30`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/VisionTurnPF.java#L30) - This is for my personal learning. Not an issue or anything. I've always found lambdas and method references confusing. Couldn't this be condensed into `RobotLgetVisionYawAngle()`?
* [`commands/VisionTurnProfiled.java`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/VisionTurnProfiled.java) - The use of LED colors to indicate robot states is fascinating. Our team oughta try it sometimes.
* [`commands/RunIntake.java L34`](https://github.com/sneakysnakesfrc/robot-2020/blob/master/src/main/java/frc/robot/commands/RunIntake.java#L34) - What does "hadi kocum" mean?

That cleans up all I have to say. If you've had enough of me, you can close the issue and I won't bother your team anymore. If you have questions, feel free to reach out of course. I hope this helped, and good luck from here on out!

**Comment by bmarap** [comment]
**Robot.java** - Using bytes might be our go-to after this comment.😁

**RobotContainer.java** - Yeah, we were using most of the commented out code as testing inputs for joysticks. We also had some autonomous code that we didn't plan using commented out. We were planning to clean it up before worlds but you know.😅

**ShooterSubsystem.java** - We were planning to use SolvePNP to get target distance and set the shooter speed accordingly. But our cell trajectories were pretty linear around target height when running at 2800-3000 RPM so we decided not to use it. We should probably remove that.

**StatusLed.java** - Good catch. I'll have a look at it.

**RunHopper.java** - Same with LEDs, will definitely have a look at this too.

**ToggleClimb.java** - We didn't know what our driver would prefer and just wrote them both.

**ToggleCompressor.java** - We had 2 huge pistons to climb. If for some reason we started with our tanks empty, it takes longer than match time to fill up the tanks. When we are aligning and setting flywheel speed, it would cause brownout if the compressor is running. We wanted a way of controlling that.

**ToggleLED.java** - Same with climber, we should probably remove them.

**VisionTurnCG.java** - Yes, I love command-based vocab as well!

**VisionTurnPF.java** - WPILib's PID Controller repeatedly calls the method to get a measurement in order to calculate the current error. If we just pass in the method as you suggested, it would have a constant value in the object. In order for it to call this method repeatedly, we either pass the method reference to constructor or just write a lambda function that it can call repeatedly. There might be a simpler way of doing this but this is how WPILib handles it.

**RunIntake.java** - We had a bug where intake and drivetrain won't work in parallel and we spend like 2 days to figure out what the problem was. @emrecandabak wanted to "encourage" the intake to work. "Hadi koçum" is a Turkish slang that roughly means "Yeah man, you can do it!". 
(P.S. it didn't work)

Thanks for your time, your feedback was quite helpful. I am glad you could learn a thing or two while looking at the code. If you have any further questions or anything you want to add, let us know by replying to the issue! I'll close the issue after a week or so. You can reach me at b.marap@gmail.com if you want to after the issue has been closed.
